version: "3.9"
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clevertec_spring
    ports:
      - "5432:5432"