spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clevertec_spring
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yml
    enabled: true
cache:
  type: LRU
  capacity: 10